using System.CodeDom.Compiler;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Il2CppInterop.SourceGenerator
{
    [Generator]
    public sealed class Il2CppValueTypeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var types = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Il2CppInterop.Common.Attributes.InjectedTypeAttribute",
                    predicate: static (node, _) =>
                        node is StructDeclarationSyntax s &&
                        s.Modifiers.Any(SyntaxKind.PartialKeyword) &&
                        s.TypeParameterList is null,   // non-generic only
                    transform: static (ctx, ct) => GetStructModel(ctx, ct))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(types, static (ctx, model) => Emit(ctx, model!));
         }

        private static StructModel? GetStructModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;
            if (ctx.TargetNode is not StructDeclarationSyntax) return null;
            var injectedTypeAttr = ctx.Attributes[0];
            var assemblyName = injectedTypeAttr.NamedArguments
                .FirstOrDefault(a => a.Key == "Assembly")
                .Value.Value as string;

            var fields = ImmutableArray.CreateBuilder<StructFieldModel>();
            int index = 0;

            foreach (var member in type.GetMembers().OfType<IFieldSymbol>())
            {
                ct.ThrowIfCancellationRequested();

                var attrs = member.GetAttributes();
                if (!attrs.Any(a => a.AttributeClass?.Name == "Il2CppFieldAttribute")) continue;

                // Same explicit-vs-default accessibility check as the class generator.

                fields.Add(new StructFieldModel(
                    FieldName: member.Name,
                    FieldType: member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    Index: index++
                ));
            }
            return new StructModel(
                Namespace: type.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : type.ContainingNamespace.ToDisplayString(),
                StructName: type.Name,
                AssemblyName: assemblyName,
                Fields: fields.ToImmutable(),
                StructAccessibility: type.DeclaredAccessibility
            );
        }
        private static string AccessibilityKeyword(Accessibility a) => a switch
        {
            Accessibility.Public               => "public",
            Accessibility.Internal             => "internal",
            Accessibility.Private              => "private",
            Accessibility.Protected            => "protected",
            Accessibility.ProtectedOrInternal  => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _                                  => "public",
        };

        private static void Emit(SourceProductionContext ctx, StructModel model)
        {
            using var sw = new StringWriter();
            using var writer = new IndentedTextWriter(sw, "    ");

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("#nullable enable");
            writer.WriteLine();

            if (model.Namespace is not null)
            {
                writer.WriteLine($"namespace {model.Namespace}");
                writer.WriteLine("{");
                writer.Indent++;
            }
            EmitPartialStruct(writer, model);
            writer.WriteLine();
            EmitInternalsClass(writer, model);
            if (model.Namespace is not null)
            {
                writer.Indent--;
                writer.WriteLine("}");
            }

            var hint = model.Namespace is null
                ? $"{model.StructName}.g.cs"
                : $"{model.Namespace}.{model.StructName}.g.cs";
            ctx.AddSource(hint, sw.ToString());
        }

        private static void EmitPartialStruct(IndentedTextWriter writer, StructModel model)
        {
            var access = AccessibilityKeyword(model.StructAccessibility);
            writer.WriteLine($"[global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals))]");
            writer.WriteLine($"{access} partial struct {model.StructName} :");
            writer.Indent++;
            writer.WriteLine($"global::Il2CppSystem.IObject,");
            writer.WriteLine($"global::Il2CppSystem.IValueType,");
            writer.WriteLine($"global::Il2CppInterop.Common.IIl2CppType,");
            writer.WriteLine($"global::Il2CppInterop.Common.IIl2CppType<{model.StructName}>");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;

            EmitBridgeMethods(writer);
            writer.WriteLine();
            EmitInstanceInterfaceMembers(writer, model);
            writer.WriteLine();
            EmitStaticInterfaceMembers(writer, model);

            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void EmitBridgeMethods(IndentedTextWriter writer)
        {
            writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod]");
            writer.WriteLine($"public global::Il2CppSystem.Boolean Equals(global::Il2CppSystem.IObject obj)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return this.Equals((object)obj);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = \"GetHashCode\")]");
            writer.WriteLine("public global::Il2CppSystem.Int32 GetIl2CppHashCode()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return this.GetHashCode();");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("[global::Il2CppInterop.Common.Attributes.Il2CppMethod(Name = \"ToString\")]");
            writer.WriteLine("public global::Il2CppSystem.String ToIl2CppString()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return this.ToString();");
            writer.Indent--;
            writer.WriteLine("}");
        }
        private static void EmitInstanceInterfaceMembers(IndentedTextWriter writer, StructModel model)
         {
             writer.WriteLine($"readonly nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass =>");
             writer.Indent++;
             writer.WriteLine($"global::Il2CppInterop.Runtime.Il2CppClassPointerStore<{model.StructName}>.NativeClassPointer;");
             writer.Indent--;
             writer.WriteLine();

             writer.WriteLine($"readonly int global::Il2CppSystem.IValueType.Size => Il2CppInternals.Size;");
             writer.WriteLine();

             writer.WriteLine($"readonly void global::Il2CppSystem.IValueType.WriteToSpan(global::System.Span<byte> span) =>");
             writer.Indent++;
             writer.WriteLine($"global::Il2CppInterop.Runtime.InteropTypes.Il2CppType.WriteToSpan(this, span);");
             writer.Indent--;
         }
        private static void EmitStaticInterfaceMembers(IndentedTextWriter writer, StructModel model)
         {
             var sn = model.StructName;

             writer.WriteLine($"static int global::Il2CppInterop.Common.IIl2CppType<{sn}>.Size => Il2CppInternals.Size;");
             writer.WriteLine();

             // ReadFromSpan — constructs via object initialiser, one field per offset
             writer.WriteLine($"static {sn} global::Il2CppInterop.Common.IIl2CppType<{sn}>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)");
             writer.WriteLine("{");
             writer.Indent++;
             writer.WriteLine("#nullable disable");
             writer.WriteLine($"return new {sn}");
             writer.WriteLine("{");
             writer.Indent++;
             foreach (var field in model.Fields)
                 writer.WriteLine($"{field.FieldName} = global::Il2CppInterop.Runtime.InteropTypes.Il2CppType.ReadFromSpanAtOffset<{field.FieldType}>(span, Il2CppInternals.FieldOffset_{field.Index}),");
             writer.Indent--;
             writer.WriteLine("};");
             writer.WriteLine("#nullable restore");
             writer.Indent--;
             writer.WriteLine("}");
             writer.WriteLine();

             // WriteToSpan — one WriteToSpanAtOffset call per field
             writer.WriteLine($"static void global::Il2CppInterop.Common.IIl2CppType<{sn}>.WriteToSpan({sn} value, global::System.Span<byte> span)");
             writer.WriteLine("{");
             writer.Indent++;
             foreach (var field in model.Fields)
                 writer.WriteLine($"global::Il2CppInterop.Runtime.InteropTypes.Il2CppType.WriteToSpanAtOffset(value.{field.FieldName}, span, Il2CppInternals.FieldOffset_{field.Index});");
             writer.Indent--;
             writer.WriteLine("}");
             writer.WriteLine();

             if (!string.IsNullOrEmpty(model.AssemblyName))
             {
                 writer.WriteLine($"static string global::Il2CppInterop.Common.IIl2CppType<{sn}>.AssemblyName => \"{model.AssemblyName}\";");
                 writer.WriteLine();
             }


             // Static constructor — kicks Il2CppInternals registration
             writer.WriteLine($"static {sn}()");
             writer.WriteLine("{");
             writer.Indent++;
             writer.WriteLine("global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);");
             writer.Indent--;
             writer.WriteLine("}");
         }
        private static void EmitInternalsClass(IndentedTextWriter writer, StructModel model)
        {
            writer.WriteLine("file static class Il2CppInternals");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("public static readonly int Size;");
            foreach (var field in model.Fields)
                writer.WriteLine($"public static readonly int FieldOffset_{field.Index};");

            writer.WriteLine();
            writer.WriteLine("static Il2CppInternals()");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine($"global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<{model.StructName}>();");
            writer.WriteLine($"Size = global::Il2CppInterop.Runtime.IL2CPP.GetIl2cppValueSize(global::Il2CppInterop.Runtime.Il2CppClassPointerStore<{model.StructName}>.NativeClassPointer);");

            foreach (var field in model.Fields)
                writer.WriteLine($"FieldOffset_{field.Index} = (int)global::Il2CppInterop.Runtime.IL2CPP.il2cpp_field_get_offset(global::Il2CppInterop.Runtime.IL2CPP.GetIl2CppField(global::Il2CppInterop.Runtime.Il2CppClassPointerStore<{model.StructName}>.NativeClassPointer, \"{field.FieldName}\"));");

            writer.WriteLine($"global::Il2CppInterop.Runtime.Runtime.Il2CppObjectPool.RegisterValueTypeInitializer<{model.StructName}>();");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
sealed record StructModel(
    string? Namespace,
    string StructName,
    string? AssemblyName,
    ImmutableArray<StructFieldModel> Fields,
    Accessibility StructAccessibility
);

sealed record StructFieldModel(
    string FieldName,
    string FieldType,
    int Index
);
