namespace Il2CppInterop.SourceGenerator.Tests;

public class InjectedClassTests : SourceGenerationTests
{
    [Test]
    public Task ClassWithNoMembers()
    {
        var testCode = """
            using Il2CppInterop.Common.Attributes;

            [InjectedType]
            public partial class Sample : Il2CppSystem.Object
            {
            }
            """;

        var expectedGeneratedCode = """
            // <auto-generated/>
            #nullable enable

            [global::Il2CppInterop.Common.Attributes.Il2CppType(typeof(Il2CppInternals))]
            public partial class Sample : global::Il2CppInterop.Common.IIl2CppType<Sample>
            {
                public Sample(global::Il2CppInterop.Common.ObjectPointer obj0) : base(obj0)
                {
                }

                static int global::Il2CppInterop.Common.IIl2CppType<Sample>.Size => nint.Size;
            
                nint global::Il2CppInterop.Common.IIl2CppType.ObjectClass => global::Il2CppInterop.Runtime.Il2CppClassPointerStore<Sample>.NativeClassPointer;

                static Sample? global::Il2CppInterop.Common.IIl2CppType<Sample>.ReadFromSpan(global::System.ReadOnlySpan<byte> span)
                {
                    return global::Il2CppInterop.Runtime.InteropTypes.Il2CppType.ReadReference<Sample>(span);
                }

                static void global::Il2CppInterop.Common.IIl2CppType<Sample>.WriteToSpan(Sample? value, global::System.Span<byte> span)
                {
                    global::Il2CppInterop.Runtime.InteropTypes.Il2CppType.WriteReference(value, span);
                }
            
                static Sample()
                {
                    global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(Il2CppInternals).TypeHandle);
                }
            }

            file static class Il2CppInternals
            {
            
                static Il2CppInternals()
                {
                    global::Il2CppInterop.Runtime.Injection.TypeInjector.RegisterTypeInIl2Cpp<Sample>();
                    global::Il2CppInterop.Runtime.Runtime.Il2CppObjectPool.RegisterInitializer(global::Il2CppInterop.Runtime.Il2CppClassPointerStore<Sample>.NativeClassPointer, ptr => new Sample(ptr));
                }
            }

            """;

        return TestGeneration(testCode, "Sample.g.cs", expectedGeneratedCode);
    }
}
